spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/batch?autoReconnect=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: inno
    password: Escape2022!@#
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  config:
    activate:
      on-profile: dev